services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    container_name: aws_prj
    environment:
      - POSTGRES_DB=aws
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7-alpine
    container_name: redis
    ports: 
      - "6379:6379"
    volumes: 
      - redis_data:/var/lib/redis/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  pg_db:
  redis_data:
