// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcq

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID        pgtype.UUID        `json:"id"`
	Context   string             `json:"context"`
	Done      pgtype.Bool        `json:"done"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}
