// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package sqlcq

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  context
) VALUES (
  $1
) RETURNING id, context, done, created_at, updated_at
`

func (q *Queries) CreateTask(ctx context.Context, argContext string) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, argContext)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Context,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTaskById = `-- name: DeleteTaskById :exec
DELETE FROM tasks 
WHERE id = $1
`

func (q *Queries) DeleteTaskById(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskById, id)
	return err
}

const getTaskById = `-- name: GetTaskById :one
SELECT id, context, done, created_at, updated_at 
FROM tasks 
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetTaskById(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskById, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Context,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, context, done, created_at, updated_at 
FROM tasks 
ORDER BY created_at DESC 
LIMIT $1 
OFFSET $2
`

type ListTasksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Context,
			&i.Done,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskById = `-- name: UpdateTaskById :one
UPDATE tasks 
SET context = $2,
    updated_at = now() 
WHERE id = $1 
RETURNING id, context, done, created_at, updated_at
`

type UpdateTaskByIdParams struct {
	ID      pgtype.UUID `json:"id"`
	Context string      `json:"context"`
}

func (q *Queries) UpdateTaskById(ctx context.Context, arg UpdateTaskByIdParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskById, arg.ID, arg.Context)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Context,
		&i.Done,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
